language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
addons:
  code_climate:
    repo_token: 3f12d785dcf81dd2351e408e00f86af458b28a4c776edf55abe641df95a1f87f
env:
  - "RAILS_ENV=test"
before_script:
  - cd spec/dummy; bundle exec rake db:migrate; cd -
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    - nicolasganz37+travis@gmail.com
