language: ruby
rvm:
  - ruby-2.4.0
dist: trusty
addons:
  code_climate:
    repo_token: 85c4aa1d323db8705ce4821687a93c638f706e5ddb20028b799654ed6487002b
env:
  - "RAILS_ENV=test"
before_script:
  - cd spec/dummy; bundle exec rake db:migrate; cd -
  - cd spec/dummy; bin/rails db:environment:set; cd -
script:
  - bundle exec rspec
after_script:
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    - nicolasganz37+travis@gmail.com
